### ISSUE TITLE
End-to-End tests not working

### ISSUE THREAD

**Issue by rzadp** [poanetwork/bridge-ui#216] opened 2019-05-15 10:28 UTC
The e2e script is not working for me.

### Steps to reproduce

```
git clone https://github.com/poanetwork/bridge-ui.git
cd bridge-ui
git checkout --track origin/develop
git submodule update --init
npm install
cd e2e-script
./run-tests.sh
```

### Result

The tests hang forever on "Connecting"

<img width="630" alt="Screenshot 2019-05-15 at 12 01 45" src="https://user-images.githubusercontent.com/12039224/57768830-bb779500-770c-11e9-8df0-79986fd06928.png">

No errors up to this point. After a while the console starts erroring:

<img width="1006" alt="Screenshot 2019-05-15 at 12 02 50" src="https://user-images.githubusercontent.com/12039224/57768845-c6322a00-770c-11e9-91d0-048fbd5151d4.png">

### My setup

- Node v10.15.3
- npm 6.9.0
- macOS 10.14.4

**Comment by rzadp** [comment] 2019-05-15 10:28
@patitonar

**Comment by patitonar** [comment] 2019-05-15 11:22
I followed the steps to reproduce the issue and it worked OK for me. From the error it seems that the parity node is not responding. Can you provide the full logs?
Also, the only external dependencies are Docker and docker-compose. Which versions are you using?

My setup:
Node v10.15.1
npm 6.4.1
Docker version 18.09.5
docker-compose version 1.21.2

**Comment by rzadp** [comment] 2019-05-15 11:42
#### My setup:
Docker Community version 18.09.2
docker-compose version 1.23.2

Here is the output when running `run-tests.sh`.
https://gist.github.com/rzadp/54b3327c5e47dd57e1f41964e5bf1f6b
Not sure if there are some log files beside this.

**Comment by patitonar** [comment] 2019-05-15 12:11
From the logs everything looks OK.

The issue seems to be at trying to reach the parity node (and probably the ui page too) from the browser on the test that is running outside docker. For that it is using the container IPs, but It seems that you cannot access container IPs directly on mac. This works OK on linux, that's why I'm not able to reproduce the issue. 

Here is more information: https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds

I will update the code to use the exposed ports on localhost instead of container IPs and open a PR for that.

**Comment by akolotov** [comment] 2019-05-16 00:41
@rzadp @patitonar consider to create a PR for this issue in the monorepo directly.

**Comment by rzadp** [comment] 2019-05-16 07:57
> @rzadp @patitonar consider to create a PR for this issue in the monorepo directly.

I'll create the PR with these changes in the monorepo

**Comment by akolotov** [comment] 2019-05-16 13:48
So, I will close this issue.

**Closed by akolotov** 2019-05-16 13:48 UTC
Labels: review
